language: node_js
node_js: node
sudo: false
cache:
  directories:
    - node_modules
services:
  - mysql
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - mysql -e "CREATE DATABASE IF NOT EXISTS urlshortener;" -uroot
  - mysql -e "CREATE USER 'urlshortener'@'127.0.0.1' IDENTIFIED BY 'pword';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'urlshortener'@'127.0.0.1';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
  - npm prune
script:
  - npm run build
  - npm run cover
  - npm run lint -- -c tslint.travis.json
  - npm run duplication -- --limit 10
after_success:
  - npm prune --production
  - npm run semantic-release
  - greenkeeper-lockfile-upload
  - if [[ "$TRAVIS_BRANCH" =~ (master|^v[0-9]+) ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker build -t "$DOCKER_REPO_SLUG:$TRAVIS_BRANCH" .;
    docker images;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push $DOCKER_REPO_SLUG:$TRAVIS_BRANCH;
    fi
